config/routes.rb
Rails.application.routes.draw do
  get 'users/login'
  put 'users/validate_login'
  get 'users/logout'
  get 'users/dashboard'

  get 'users/index_purchase'
  post 'users/index_purchase'
  get 'users/add_purchase'
  post 'users/get_purchase'
  get 'users/show_purchase'
  patch 'users/update_purchase'
  get 'users/edit_purchase'
  get 'users/delete_purchase'
  
  get 'users/index_orderSummayForIssue'
  post 'users/index_orderSummayForIssue'
  get 'users/index_issues'
  post 'users/index_issues'
  get 'users/add_issues'
  post 'users/get_issues'
  get 'users/show_issues'
  patch 'users/update_issues'
  get 'users/edit_issues'
  get 'users/delete_issues'
  
  get 'users/index_productionForLabour'
  post 'users/index_productionForLabour'
  get 'users/index_labour'
  post 'users/index_labour'
  get 'users/add_labour'
  post 'users/get_labour'
  get 'users/show_labour'
  patch 'users/update_labour'
  get 'users/edit_labour'
  get 'users/delete_labour'
  
  get 'users/add_orderSummary'
  post 'users/get_order'
  get 'users/show_orderSummary'
  patch 'users/update_orderSummary'
  get 'users/edit_orderSummary'
  get 'users/index_orderSummary'
  post 'users/index_orderSummary'
  get 'users/delete_orderSummary'
  
  get 'users/add_productionReport'
  post'users/get_production'
  get 'users/index_issuesForProduction'
   post 'users/index_issuesForProduction'
  get 'users/index_productionReport'
  post 'users/index_productionReport'
  post 'users/update_productionReport' 
  patch 'users/update_productionReport'
  get 'users/edit_productionReport' 
  get 'users/show_productionReport'
  get 'users/delete_productionReport'
  
  get 'users/machine_maintenance'
  post 'users/get_machine'
  patch 'users/update_machine'
  get 'users/edit_machine'
  get 'users/show_machine'
  get 'users/delete_machine'
  get 'users/index_machineMaintenance'
  post 'users/index_machineMaintenance'
  
  get 'users/machine_time'
  post 'users/machine_time'
  get 'users/machine_time_create'
 post 'users/machine_time_create'
 get  'users/machine_time_delete'
 
 get 'users/report_mould_history'
 post 'users/report_mould_history'

get 'users/mould_history_report'
post 'users/mould_history_report'
get 'users/mould_history_xls'

 
  get 'users/index_admin'
  post 'users/index_admin'

  patch 'users/index_admin'
  get 'users/admin_create'
  post 'users/admin_create'

  get 'users/insert_material_new'
  post 'users/insert_material_new'
  get 'users/insert_material_create'
  post 'users/insert_material_create'
  get 'users/insert_material_delete'
  post 'users/insert_material_delete'

  get 'users/purchase_type_new'
  post 'users/purchase_type_new'
  get 'users/purchase_type_create'
  post 'users/purchase_type_create'
  get 'users/purchase_type_delete'
  post 'users/purchase_type_delete'

  get 'users/reground_new'
  post 'users/reground_new'
  get 'users/reground_create'
  post 'users/reground_create'
  get 'users/reground_delete'
  post 'users/reground_delete'

  get 'users/chemical_new'
  post 'users/chemical_new'
  get 'users/chemical_create'
  post 'users/chemical_create'
  get 'users/chemical_delete'
  post 'users/chemical_delete'

  get 'users/chemical_type_new'
  post 'users/chemical_type_new'
  get 'users/chemical_type_delete'
  post 'users/chemical_type_delete'
  get 'users/chemical_type_create'
  post 'users/chemical_type_create'

  get 'users/raw_material_new'
  post 'users/raw_material_new'
  get 'users/raw_create'
  post 'users/raw_create'
  get 'users/raw_delete'
  post 'users/raw_delete'

  get 'users/party_order_new'
  post 'users/party_order_new'
  get 'users/party_order_create'
  post 'users/party_order_create'
  get "users/party_order_delete"
  post "users/party_order_delete"

  get 'users/party_purchase_new'
  post 'users/party_purchase_new'
  get 'users/party_purchse_create'
  post 'users/party_purchse_create'
  get 'users/party_purchse_delete'
  post 'users/party_purchse_delete'
 
  get 'users/mach_use_new'
  post 'users/mach_use_new'
  get 'users/machine_use_create'
  post 'users/machine_use_create'
  get 'users/machine_use_delete'
  post 'users/machine_use_delete'

  get 'users/mould_new'
  post 'users/mould_new'
  get 'users/mould_create'
  post 'users/mould_create'
  get 'users/mould_delete'
  post 'users/mould_delete'

   get 'users/supervisor_new'
  post 'users/supervisor_new'
  get 'users/supervisor_create'
  post 'users/supervisor_create'
  get 'users/supervisor_delete'
  post 'users/supervisor_delete'

  get 'users/cost_new'
  post 'users/cost_new'
  get 'users/cost_create'
  post 'users/cost_create'
  get 'users/edit_cost'
  patch 'users/update_cost'
  post 'users/update_cost'
  get 'users/cost_delete'
  post 'users/cost_delete'

  get 'users/goods_new'
  post 'users/goods_new'
  get 'users/goods_create'
  post 'users/goods_create'
   get 'users/goods_delete'
  post 'users/goods_delete'

  get 'users/nature_new'
  post 'users/nature_new'
  get 'users/nature_create'
  post 'users/nature_create'
  get 'users/nature_delete'
  post 'users/nature_delete'

  get 'users/reason_for_idle_new'
  post 'users/reason_for_idle_new'
  get 'users/reasonforidle_create'
  post 'users/reasonforidle_create'
  get 'users/reasonforidle_delete'
  post 'users/reasonforidle_delete'

  get 'users/rejection_reason_new'
  post 'users/rejection_reason_new'
  get 'users/rejection_reason_create'
  post 'users/rejection_reason_create'
  get 'users/rejection_reason_delete'
  post 'users/rejection_reason_delete'

  get 'users/new'
  post 'users/create'
  post 'users/new'
  get 'users/user_index'
  post 'users/user_index'
  get 'users/user_destroy'
  post 'users/user_destroy' 

 

  get 'users/trash_orderSummary'
  get 'users/trash_labour'
  get 'users/trash_issue'
  get 'users/trash_purchase'
  get 'users/trash_production'
  get 'users/trash_machine_maintenance'

  get 'users/trash_showOrderSummary'
  get 'users/trash_showLabour'
  get 'users/trash_showIssue'
  get 'users/trash_showPurchase'
  get 'users/trash_showProduction'
  get 'users/trash_showMachineMaintenance'

  get 'users/delete_trashOrderSummary'
  get 'users/delete_trashIssue'
  get 'users/delete_trashLabour'
  get 'users/delete_trashPurchase'
  get 'users/delete_trashProduction'
  get 'users/delete_trashMachine'

  get 'users/restore_trashOrderSummary'
  get 'users/restore_trashIssue'
  get 'users/restore_trashLabour'
  get 'users/restore_trashPurchase'
  get 'users/restore_trashProduction'
  get 'users/restore_trashMachine'
 
  
  get 'users/yield_cost'
  post 'users/yield_cost_report'
  get 'users/yield_cost_report_xls'

  get 'users/idle_time_report'
  post 'users/idle_time_report'
  get 'users/idle_time_report_xls'

  get 'users/report_rejection_analysis'
  get 'users/report_rejection_analysis'
  
  get 'users/rejection_analysis'
  post 'users/rejection_analysis'

  get 'users/rejection_analysis_xls_report'

  get 'users/order_summary_report'
  post 'users/order_summary_report'

  get 'users/order_sum_report'
  post 'users/order_sum_report'
  

  get 'users/purchase_report'
  post 'users/purchase_report'

  get 'users/purchase_sum_report'
  post 'users/purchase_sum_report'

  get 'users/issues_report'
  post 'users/issues_report'

  get 'users/issue_report'
  post 'users/issue_report'

  get 'users/productn_report'
  post 'users/productn_report'

  get 'users/product_report'
  post 'users/product_report'

  get 'users/supervisor_name'
  post 'users/supervisor_name'

  get 'users/report_purchase'
  post 'users/report_purchase'

  get 'users/report_order_summary'
  post 'users/report_order_summary'

  get 'users/report_issues'
  post 'users/report_issues'

  get 'users/report_production'
  post 'users/report_production'

  get 'users/report_idle_time'
  post 'users/report_idle_time'

  get 'users/report_machine_maintenance'
  post 'users/report_machine_maintenance'

  get 'users/machine_maintenance_report'
  post 'users/machine_maintenance_report'
  get 'users/machine_maintenance_xls_report'

  get 'users/report_oee'
  get 'users/report_oee'
  
  get 'users/oee_report'
  post 'users/oee_report'

  get 'users/oee_xls_report'
  
   get 'users/report_qty_after_rg'
  get 'users/report_qty_after_rg'

  get 'users/qty_after_rg'
  post 'users/qty_after_rg'

  get 'users/qty_after_rg_xls_report'
 
  get 'users/pending_order'
  post 'users/pending_order'

  get 'users/lab_report'
  get 'users/labour_report'
  get 'users/report_labour'
  post 'users/lab_report'
  post 'users/labour_report'
  post 'users/report_labour'

  resources :users

  root 'users#login'

end

app/models/user.rb
class User < ActiveRecord::Base
#acts_as_paranoid
#belongs_to :admin
validates :name, uniqueness: true,:presence => { :message => " cannot be blank" }
validates :password, length: { in: 6..20 }, confirmation: true, :presence => { :message => " cannot be blank" }
validates :password_confirmation,length: { in: 6..20 }, :presence => { :message => " cannot be blank" }
validates :role, :presence => true
validates :name, :password, :password_confirmation, presence: true
# before_save :encrypt_password
#  def encrypt_password
  # password = "abc-facebook" if password.blank?
#    self.password = Digest::MD5.hexdigest(password)
#  end

 #def self.authenticate(email, password)
 #  @user=User.where(:name=>name, :password=> Digest::MD5.hexdigest(password))
 #  @user ? @user:nil
 # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cost_new.html.erb
<div class="bod">
  <div class="col-md-10 col-sm-8 body-wrap">
<div class="set">
<div class="body-container">
<div class="body-header">
 Power Cost per unit
</div>
<div class="body-content">
<div class="table-container">
<div class="header">
    List of Power Cost per unit
</div>
<table class="table">
    <thead>
<tr>
<th>Cost per unit</th>
<th> Action</th>
</tr>
</thead>


<tbody>

<%= form_for([@cost], validate: true, :url=>{:controller=>"users", :action => "update_cost"}) do |i|%>

<tr class="odd"><td><%=i.text_field :cost_per_unit,:required => true%></td>
<td><%= i.submit "Update",:class=>"btn btn-info"%></td></tr>
<%end%>




<tr class="odd"><td><div class = "fot"> Old Cost &nbsp; => &nbsp; <%= @cost1.cost_per_unit %></div></td>
</tr>

</tbody>

</table>
</div>
</div>
</div>
</div>
</div>            

app/views/users/edit_purchase.html.erb
<div class="bod">
	<div class="col-md-10 col-sm-8 body-wrap">
	<div class="body-container">
                  <div class="body-header">
                      Edit Purchase Summary
  <div class="add"><%= link_to users_index_purchase_path, class: "btn btn-default",:title => 'List', :rel => 'tooltip' do%>
<i class="fa fa-list"></i><%end%>
</div>
                    </div>
                    <div class="body-content">
                        <div class="table-container">


<%= form_for @purchase, :url=>{:action => "update_purchase", :id => @purchase } do |i| %>
<%= @purchase.errors.full_messages.first if @purchase.errors.any? %><div class="table1">
<div class="col-md-4">
	<div style="width: 79%; margin-left: 8%;">
<table class="table">

<tr><td><%= i.label :grn_no,"GRN No"%></td></tr>
<tr><td><%= i.number_field :grn_no,:required => true%></td></tr>
<tr><td><%= i.label :date," Date" ,:class=>"fa fa-calendar"%></td></tr>
<tr><td><%= i.text_field :date,:id=>"txtFrom",:required => true%></td></tr>
<tr><td><%= i.label :party%></td></tr>
<tr><td>
<%= i.collection_select(:party, PartyPurchase.select(:party_purchase_list).order('party_purchase_list ASC').uniq, :party_purchase_list, :party_purchase_list, {:prompt=> '--select--'},{:required => true})%> </td></tr>
<tr><td><%= i.label :trading_material,"Trading Material"%></td></tr>
<tr><td>
<%= i.collection_select(:trading_material, TypeOfPurchase.select(:purchase_type).order('purchase_type ASC').uniq, :purchase_type, :purchase_type, {:prompt=> '--select--'},{:required => true})%> </td></tr>

<tr><td><%= i.label :item%></td></tr>
<tr><td><!--%= i.text_field :item,:required => true%-->
<%= i.collection_select(:item, RawMaterial.select(:raw_material_list).order('raw_material_list ASC').uniq, :raw_material_list, :raw_material_list,{:prompt=>"--select--"},{:required => true})%></td></tr>
</table>
</div>
</div>

<div class="col-md-4">
	<div style="padding: 8px 22px 20px 18px; width:79%">
<table class="table">

<tr><td><%= i.label :desc,"Bill Quantity"%></td></tr>
<tr><td><%= i.text_field :desc,:required => true%></td></tr>
<tr><td><%= i.label :qty_received%></td></tr>
<tr><td><%= i.number_field :qty_received, :step => "0.001", :id=>"txt2", :onkeyup=>"div()", :required => true%></td></tr>
<tr><td><%= i.label :qty_accepted%></td></tr>
<tr><td><%= i.number_field :qty_accepted, :step => "0.001", :id=>"txt3", :onkeyup=>"div()", :required => true%></td></tr>
<tr><td><%= i.label :rejected%></td></tr>
<tr><td><%= i.text_field :rejected,:style=>"background:#1B5C90;color:#fff;", :value => (number_with_precision(i.object.rejected, :precision => 2)),:id=>"txt5",:onkeyup=>"div()",:readonly=> "true"%></td></tr>

</table>
</div>
</div>

<div class="col-md-4">
	<div style="width: 79%;">
<table class="table">

<tr><td><%= i.label :bill_value%></td></tr>
<tr><td><%= i.number_field :bill_value,:step => "0.001",:id=>"txt1",:onkeyup=>"div()",:required => true%></td></tr>
<tr><td><%= i.label :rate,"Rate Per Kgs"%></td></tr>
<tr><td><%= i.number_field :rate,:style=>"background:#1B5C90;color:#fff;",:step => "0.001",:id=>"txt4",:onkeyup=>"div()",:readonly=> "true"%></td></tr>
<tr><td><%= i.label :debit%></td></tr>
<tr><td><%= i.number_field :debit,:style=>"background:#1B5C90;color:#fff;",:id=>"txt6",:readonly=> "true"%></td></tr>
<tr><td><%= i.label :reasons%></td></tr>
<tr><td><%= i.text_field :reasons %></td></tr>
<%= i.hidden_field :created_by,:value => @user %>

</table>
</div>
</div>
</div>
<div class="col-md-12">
<center>
<table>
<tr><td><%= i.submit "Update",:class=>"btn btn-info btn-sm"%></div>
<%end%>
</td></tr>
</table>
</center>
</div>
</div>
</div>
</div>
</div>

app/views/users/idle_time_report.html.erb
<div class = "bod">
  <div class="col-md-10 col-sm-8 body-wrap">
              <div class="body-container">
                  <div class="body-header">
                      Idle Time Report
<div class="add"><%= link_to users_report_idle_time_path, class: "btn btn-default", :title => 'Back', :rel =>'tooltip' do%>
<i class="fa fa-arrow-left"></i><%end%></div>

                     <%if admin? and not @ss.blank?%>
<div class="down"><%= link_to users_idle_time_report_xls_path(format: "xls"),:class=>"btn btn-info btn-sm" do%>
<i class="fa fa-arrow-circle-down">Download</i><%end%></div><br>
<%end%></div>
                    <div class="body-content">
                       <div class="table-container">
      <table class="table">                        
 <thead>
 <tr>   
<th>Issue date </th>                                                        
<th>Shift</th>
<th>Machine</th>
<th>Product name</th>
<th>Mould</th>
<th>Expected qty</th>
<th>Actual qty</th>
<th>Number of minutes idle</th>
<th>Reason</th>
<th>Supervisor</th>
</tr>
</thead>
<% if @ss.blank? then %>
<table><th>No records to display</th></table>

<%else%>
<ul id= "Labour">

<%$ss = @ss%>
<% @ss.each do |i| %>
<tr>
<% i.each do |j|%>
<td><%= j%></td>
<%end%>
<%end%>
</table>
</div>

<% end %>

</div>
</div>
</div>

app/views/users/index_purchase.html.erb
<div class="bod">
  <div class="col-md-10 col-sm-8 body-wrap">
<div class="body-container">
                  <div class="body-header">
                      Purchase Summary
                      <div class="add">
<% if not admin? %>
<%= link_to users_add_purchase_path, class: "btn btn-default",:title => 'Add', :rel => 'tooltip' do%>
<i class="fa fa-plus"></i><%end%>
<%end%>
						</div>
                    </div>
                    <div class="body-content">
                        <div class="table-container">
                              <div class="header">
                                  List of Purchase
                               <div class="search"><%= form_tag(:action => "index_purchase", :method => 'get', id:"search-order") do %>
   <p> <span ><%= text_field_tag :search, params[:search],:placeholder=>"Grn No /  Party",:class=>"fa fa-search"%></span>
   <div class="bbtn">
    <%= submit_tag "Search",:class=>"btn btn-info btn-sm"%>
     <%= link_to "clear" ,users_index_purchase_path,:class=>"btn btn-info btn-sm"%>
    </div></p>
   <% end %></div>
                                </div>
                                <table class="table">
    <thead>
<tr>
<th>Sl.No</th>
<th>GRN No</th>
<th>Party</th>
<th>Trading Material</th>
<th>Item</th>

<!--%if factory?%>
<th>Created by</th>
<th>Updated by</th>
<!-th>Created at</th->
<-th>Updated at</th->
<-%end%-->

<th colspan="3"><center>Action</center></th>
</tr>
</thead>

<% if @purchase.blank? then %>
<table><th>No records to display</th></table>

<% else %>


<ul id = "Purchase" >
<%t=0%>
<% @purchase.each do |i| %>
<%t=t+1%>
<tbody>
<tr class="odd">
<td><%= t %></td>
<td><%= i.grn_no%></td>
<td><%= i.party%></td>
<td><%= i.trading_material%></td>
<td><%= i.item%></td>
<%if admin?%>
<td><center><%= link_to users_show_purchase_path(:id => i.id), class: "btn btn-default",:title => 'Show', :rel => 'tooltip' do%>
<i class="fa fa-eye"></i><%end%></center></td>
<%end%>
<%if factory?%>
<!--td><-%= i.created_by %-></td-->
<!--td><-%= i.updated_by %-></td-->
<!--td><div class="fot"><-%= i.created_at.strftime("%Y-%m-%d")%></div></td-->
<!--td><div class="fot"><-%= i.updated_at.strftime("%Y-%m-%d")%-></div></td-->
<td><%= link_to users_show_purchase_path(:id => i.id), class: "btn btn-default",:title => 'Show', :rel => 'tooltip' do%>
<i class="fa fa-eye"></i><%end%></td>

<td><%= link_to users_edit_purchase_path(:id => i.id), class: "btn btn-default",:title => 'Edit', :rel => 'tooltip' do%>
<i class="fa fa-pencil"></i><%end%>
</td>
<td><%= link_to image_tag("/assets/trash1.png", height: '20', width: '20',:class=>"img-circle",:title => 'Delete', :rel => 'tooltip',:onclick=>"if (confirm('Are you sure!!!')) commentDelete(1); return false"),{:action => 'delete_purchase', :id => i.id }%>
</td>

<%end%>

<% if operator?%>
<td><center><%= link_to users_show_purchase_path(:id => i.id), class: "btn btn-default",:title => 'Show', :rel => 'tooltip' do%><i class="fa fa-eye"></i><%end%></center></td>

<%unless i.updated_at <(Time.now- 7.day)%>
<td><%= link_to users_edit_purchase_path(:id => i.id), class: "btn btn-default",:title => 'Edit', :rel => 'tooltip' do%>
<i class="fa fa-pencil"></i><%end%></td>
<td><%= link_to image_tag("/assets/trash1.png", height: '20', width: '20',:class=>"img-circle",:title => 'Delete', :rel => 'tooltip',:onclick=>"if (confirm('Are you sure!!!')) commentDelete(1); return false"),{:action => 'delete_purchase', :id => i.id }%>
</td>

<%end%>
<%end%>
</tr>
<%end%>
</table>
<%end%>
</div>
</div>
</div>
<div class="digg_pagination" align="right">
<%= will_paginate @purchase, :container => false %>
</div>
<!--div class="fott">
<div class="digg_pagination">
    <!%= will_paginate @purchase, :container => false %>
  </div>
</div-->

</div>

app/views/users/reground_new.html.erb
<div class="bod">
  <div class="col-md-10 col-sm-8 body-wrap">
<div class="set">
<div class="body-container">
<div class="body-header">
Reground Issues
<div class="fact"><%= form_tag(:action => "reground_new", :method => 'get', id:"search-order") do %>
   <p>
   <span ><%= text_field_tag :search, params[:search],:placeholder=>"Reground",:class=>"fa fa-search"%></span>
   <div class="fact1">
    <%= submit_tag "Search",:class=>"btn btn-info btn-sm"%>
  <%= link_to "clear" ,users_reground_new_path,:class=>"btn btn-info btn-sm"%>
</div>   </p>
   <% end %></div>
</div>
<div class="body-content">
<div class="table-container">
<div class="header">
    List of Reground Issues
</div>
<table class="table">
<thead>
<tr>
<th>Reground</th>
<th>Action</th>
</thead>
<tbody>
<%= form_for([@reground], validate: true, :url=>{:controller=>"users", :action => "reground_create"}) do |i|%>
<tr><td><%=i.text_field:reground_list,:required => true %>
<td align="center"><%= i.submit "Add",:class=>"btn btn-info"%>
 <%end%></td></tr>

<% @reground1.each do |i| %>
<tr>
<td><div class="fot"><%= i.reground_list%></div></td>
<td><%= link_to image_tag("/assets/trash1.png", height: '20', width: '20',:class=>"img-circle",:title => 'Delete', :rel => 'tooltip',:onclick=>"if (confirm('Are you sure!!!')) commentDelete(1); return false"),{:action => 'reground_delete', :id => i.id }%></td>

</tr>
<%end%>
</tbody>
</table>
</div>
</div>
<div class="digg_pagination" align="right">
    <%= will_paginate  @reground1, :container => false %>
  </div>
</div>
</div>
</div>

app/views/users/trash_showPurchase.html.erb
<div class="bod">
<div class="col-md-10 col-sm-8 body-wrap">
<div class="body-container">
<div class="body-header">
<h4>Show Purchase </h4>
</div>
<div class="body-content">
<div class="table-container">

<div class="popup-wrapper" id="popup"><div class="popup-container">
<h3 align = "right"><b>
<%= link_to "", users_trash_purchase_path, class:"fa fa-close" %></b></h3>
<table class="table">
<tr><td>GRN No:</td>
<td><%= @purchase.grn_no %></td></tr>
<tr><td>Date:</td>
<td><%= @purchase.date %></td></tr>
<tr><td>Party:</td>
<td><%= @purchase.party%></td></tr>
<tr><td>Trading Material:</td>
<td><%= @purchase.trading_material %></td></tr>
<tr><td>Item:</td>
<td><%= @purchase.item %></td></tr>
<tr><td>Bill Quantity:</td>
<td><%= @purchase.desc %></td></tr>
<tr><td>Qty Received </td>
<td><%= @purchase.qty_received %></td></tr>
<tr><td>Qty Accepted:</td>
<td><%= @purchase.qty_accepted %></td></tr>
<tr><td>Rejected:</td>
<td><%= @purchase.rejected %></td></tr>
<tr><td>Bill Value:</td>
<td><%= @purchase.bill_value %></td></tr>
<tr><td>Rate:</td>
<td><%= @purchase.rate.to_f.round(2) %></td></tr>
<tr><td>Debit:</td>
<td><%= @purchase.debit.to_f.round(2)%></td></tr>
<tr><td>Reasons:</td>
<td><%= @purchase.reasons %></td></tr>
<tr><td>Created_by</td>
<td><%= @purchase.created_by %></td></tr>
<tr><td>Updated_by:</td>
<td><%= @purchase.updated_by %></td></tr>
<tr><td>Created_at:</td>
<td><%= @purchase.created_at.strftime("%m/%d/%y") %></td></tr>
<tr><td>Updated_at:</td>
<td><%= @purchase.updated_at.strftime("%m/%d/%y")%></td></tr>
</table>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/users/yield_cost_report.html.erb
<div class = "bod">
  <div class="col-md-10 col-sm-8 body-wrap">
              <div class="body-container">
                  <div class="body-header">
                      Yield and Cost
<div class="add"><%= link_to users_yield_cost_path, class: "btn btn-default", :title => 'Back', :rel =>'tooltip' do%>
<i class="fa fa-arrow-left"></i><%end%></div>

                     <%if admin? and not @arr.blank?%>
<div class="down"><%= link_to users_yield_cost_report_xls_path(format: "xls"),:class=>"btn btn-info btn-sm" do%>
<i class="fa fa-arrow-circle-down">Download</i><%end%></div><br>
<%end%></div>
<div class="body-content">
<div class="table-container">
      <table class="table">
 <thead>
 <tr>
<th>Machine</th>
<th>Product name</th>
<th>Mould</th>
<th>Raw Material</th>
<th>Product Weight</th>
<th>Actual qty</th>
<th>Rejected qty</th>
<th>Wastage Qty</th>
<th>Wastage %</th>
<th>Cost per Kg</th>
<th>Cost Pc</th>
<th>Yield %</th>
</tr>
</thead>
 
<% if @arr.blank? then %>
<table><th>No records to display</th></table>

<% else %>
<ul id= "Issues">

<% $arr = @arr%>
<% @arr.each do |i| %>
<tr class="odd">
<td><%= i[1] %></td>
<td><%= i[2] %></td>
<td><%= i[3] %></td>
<td><%= i[4] %></td>
<td><%= i[6] %></td>
<td><%= i[7] %></td>
<td><%= i[8] %></td>
<td><%= i[10] %></td>
<td><%= i[11] %></td>
<td><%= i[12] %></td>
<td><%= i[13] %></td>
<%ye =((i[7].to_f/(i[7].to_f+i[8].to_f+i[9].to_f))*100).round(2)%>
<td><%= ye%></td>
</tr>

<% end %>
</table>
<%end%>
</div>
</div>
</div>
