config/routes.rb
Rails.application.routes.draw do
  get 'users/login'
  put 'users/validate_login'
  get 'users/logout'
  get 'users/dashboard'

  get 'users/index_purchase'
  post 'users/index_purchase'
  get 'users/add_purchase'
  post 'users/get_purchase'
  get 'users/show_purchase'
  patch 'users/update_purchase'
  get 'users/edit_purchase'
  get 'users/delete_purchase'
  
  get 'users/index_orderSummayForIssue'
  post 'users/index_orderSummayForIssue'
  get 'users/index_issues'
  post 'users/index_issues'
  get 'users/add_issues'
  post 'users/get_issues'
  get 'users/show_issues'
  patch 'users/update_issues'
  get 'users/edit_issues'
  get 'users/delete_issues'
  
  get 'users/index_productionForLabour'
  post 'users/index_productionForLabour'
  get 'users/index_labour'
  post 'users/index_labour'
  get 'users/add_labour'
  post 'users/get_labour'
  get 'users/show_labour'
  patch 'users/update_labour'
  get 'users/edit_labour'
  get 'users/delete_labour'
  
  get 'users/add_orderSummary'
  post 'users/get_order'
  get 'users/show_orderSummary'
  patch 'users/update_orderSummary'
  get 'users/edit_orderSummary'
  get 'users/index_orderSummary'
  post 'users/index_orderSummary'
  get 'users/delete_orderSummary'
  
  get 'users/add_productionReport'
  post'users/get_production'
  get 'users/index_issuesForProduction'
   post 'users/index_issuesForProduction'
  get 'users/index_productionReport'
  post 'users/index_productionReport'
  post 'users/update_productionReport' 
  patch 'users/update_productionReport'
  get 'users/edit_productionReport' 
  get 'users/show_productionReport'
  get 'users/delete_productionReport'
  
  get 'users/machine_maintenance'
  post 'users/get_machine'
  patch 'users/update_machine'
  get 'users/edit_machine'
  get 'users/show_machine'
  get 'users/delete_machine'
  get 'users/index_machineMaintenance'
  post 'users/index_machineMaintenance'
  
  get 'users/machine_time'
  post 'users/machine_time'
  get 'users/machine_time_create'
 post 'users/machine_time_create'
 get  'users/machine_time_delete'
 
 get 'users/report_mould_history'
 post 'users/report_mould_history'

get 'users/mould_history_report'
post 'users/mould_history_report'
get 'users/mould_history_xls'

 
  get 'users/index_admin'
  post 'users/index_admin'

  patch 'users/index_admin'
  get 'users/admin_create'
  post 'users/admin_create'

  get 'users/insert_material_new'
  post 'users/insert_material_new'
  get 'users/insert_material_create'
  post 'users/insert_material_create'
  get 'users/insert_material_delete'
  post 'users/insert_material_delete'

  get 'users/purchase_type_new'
  post 'users/purchase_type_new'
  get 'users/purchase_type_create'
  post 'users/purchase_type_create'
  get 'users/purchase_type_delete'
  post 'users/purchase_type_delete'

  get 'users/reground_new'
  post 'users/reground_new'
  get 'users/reground_create'
  post 'users/reground_create'
  get 'users/reground_delete'
  post 'users/reground_delete'

  get 'users/chemical_new'
  post 'users/chemical_new'
  get 'users/chemical_create'
  post 'users/chemical_create'
  get 'users/chemical_delete'
  post 'users/chemical_delete'

  get 'users/chemical_type_new'
  post 'users/chemical_type_new'
  get 'users/chemical_type_delete'
  post 'users/chemical_type_delete'
  get 'users/chemical_type_create'
  post 'users/chemical_type_create'

  get 'users/raw_material_new'
  post 'users/raw_material_new'
  get 'users/raw_create'
  post 'users/raw_create'
  get 'users/raw_delete'
  post 'users/raw_delete'

  get 'users/party_order_new'
  post 'users/party_order_new'
  get 'users/party_order_create'
  post 'users/party_order_create'
  get "users/party_order_delete"
  post "users/party_order_delete"

  get 'users/party_purchase_new'
  post 'users/party_purchase_new'
  get 'users/party_purchse_create'
  post 'users/party_purchse_create'
  get 'users/party_purchse_delete'
  post 'users/party_purchse_delete'
 
  get 'users/mach_use_new'
  post 'users/mach_use_new'
  get 'users/machine_use_create'
  post 'users/machine_use_create'
  get 'users/machine_use_delete'
  post 'users/machine_use_delete'

  get 'users/mould_new'
  post 'users/mould_new'
  get 'users/mould_create'
  post 'users/mould_create'
  get 'users/mould_delete'
  post 'users/mould_delete'

   get 'users/supervisor_new'
  post 'users/supervisor_new'
  get 'users/supervisor_create'
  post 'users/supervisor_create'
  get 'users/supervisor_delete'
  post 'users/supervisor_delete'

  get 'users/cost_new'
  post 'users/cost_new'
  get 'users/cost_create'
  post 'users/cost_create'
  get 'users/edit_cost'
  patch 'users/update_cost'
  post 'users/update_cost'
  get 'users/cost_delete'
  post 'users/cost_delete'

  get 'users/goods_new'
  post 'users/goods_new'
  get 'users/goods_create'
  post 'users/goods_create'
   get 'users/goods_delete'
  post 'users/goods_delete'

  get 'users/nature_new'
  post 'users/nature_new'
  get 'users/nature_create'
  post 'users/nature_create'
  get 'users/nature_delete'
  post 'users/nature_delete'

  get 'users/reason_for_idle_new'
  post 'users/reason_for_idle_new'
  get 'users/reasonforidle_create'
  post 'users/reasonforidle_create'
  get 'users/reasonforidle_delete'
  post 'users/reasonforidle_delete'

  get 'users/rejection_reason_new'
  post 'users/rejection_reason_new'
  get 'users/rejection_reason_create'
  post 'users/rejection_reason_create'
  get 'users/rejection_reason_delete'
  post 'users/rejection_reason_delete'

  get 'users/new'
  post 'users/create'
  post 'users/new'
  get 'users/user_index'
  post 'users/user_index'
  get 'users/user_destroy'
  post 'users/user_destroy' 

 

  get 'users/trash_orderSummary'
  get 'users/trash_labour'
  get 'users/trash_issue'
  get 'users/trash_purchase'
  get 'users/trash_production'
  get 'users/trash_machine_maintenance'

  get 'users/trash_showOrderSummary'
  get 'users/trash_showLabour'
  get 'users/trash_showIssue'
  get 'users/trash_showPurchase'
  get 'users/trash_showProduction'
  get 'users/trash_showMachineMaintenance'

  get 'users/delete_trashOrderSummary'
  get 'users/delete_trashIssue'
  get 'users/delete_trashLabour'
  get 'users/delete_trashPurchase'
  get 'users/delete_trashProduction'
  get 'users/delete_trashMachine'

  get 'users/restore_trashOrderSummary'
  get 'users/restore_trashIssue'
  get 'users/restore_trashLabour'
  get 'users/restore_trashPurchase'
  get 'users/restore_trashProduction'
  get 'users/restore_trashMachine'
 
  
  get 'users/yield_cost'
  post 'users/yield_cost_report'
  get 'users/yield_cost_report_xls'

  get 'users/idle_time_report'
  post 'users/idle_time_report'
  get 'users/idle_time_report_xls'

  get 'users/report_rejection_analysis'
  get 'users/report_rejection_analysis'
  
  get 'users/rejection_analysis'
  post 'users/rejection_analysis'

  get 'users/rejection_analysis_xls_report'

  get 'users/order_summary_report'
  post 'users/order_summary_report'

  get 'users/order_sum_report'
  post 'users/order_sum_report'
  

  get 'users/purchase_report'
  post 'users/purchase_report'

  get 'users/purchase_sum_report'
  post 'users/purchase_sum_report'

  get 'users/issues_report'
  post 'users/issues_report'

  get 'users/issue_report'
  post 'users/issue_report'

  get 'users/productn_report'
  post 'users/productn_report'

  get 'users/product_report'
  post 'users/product_report'

  get 'users/supervisor_name'
  post 'users/supervisor_name'

  get 'users/report_purchase'
  post 'users/report_purchase'

  get 'users/report_order_summary'
  post 'users/report_order_summary'

  get 'users/report_issues'
  post 'users/report_issues'

  get 'users/report_production'
  post 'users/report_production'

  get 'users/report_idle_time'
  post 'users/report_idle_time'

  get 'users/report_machine_maintenance'
  post 'users/report_machine_maintenance'

  get 'users/machine_maintenance_report'
  post 'users/machine_maintenance_report'
  get 'users/machine_maintenance_xls_report'

  get 'users/report_oee'
  get 'users/report_oee'
  
  get 'users/oee_report'
  post 'users/oee_report'

  get 'users/oee_xls_report'
  
   get 'users/report_qty_after_rg'
  get 'users/report_qty_after_rg'

  get 'users/qty_after_rg'
  post 'users/qty_after_rg'

  get 'users/qty_after_rg_xls_report'
 
  get 'users/pending_order'
  post 'users/pending_order'

  get 'users/lab_report'
  get 'users/labour_report'
  get 'users/report_labour'
  post 'users/lab_report'
  post 'users/labour_report'
  post 'users/report_labour'

  resources :users

  root 'users#login'

end

app/views/layouts/_footer.html.erb
<div class="row">
<div class="col-md-12">
<div class="navbar navbar-default navbar-fixed-bottom">
<div class="container">
<p align="center" style="color:#E56621;" ><i class="fa fa-copyright">2016Copyright White Plaast</i></p>
</div>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<% if not session[:user_id].blank?%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= image_tag "dash-logo.png"%> Whiteplast</title>
    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">

    <!--link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet"-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"
            type="text/javascript"></script>
    <!--link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/start/jquery-ui.css"
          rel="Stylesheet" type="text/css" /-->


  </head>
  <body>
  
  <div class="dash-top">
      <div class="container-fluid"> 
          <div class="row">
              <div class="col-md-2 col-sm-4 logo-left nopad">
                  <div class="clearfix"></div>
                  <%= image_tag "dash-logo.png"%>
                      <div class="sandwich"><%= image_tag "sandwich-icon.png"%></div>
                </div>
                <div class="col-md-1 col-sm-2 col-xs-3 horn-icon nopad">
                  <%= image_tag "speaker-icon.png"%>
                </div> 
                <div class="col-md-5 col-sm-6 col-xs-7 horn-text nopad">
                  <marquee direction="alternate">Quality, design and performance are the three pillars of our offerings</marquee>
                </div>
                <div class="col-md-4 nopad">
                  <div class="userinfo">
                      <%= image_tag  "user-img.png"%>
                        <span><%= @user %></span>
                    </div>
                    <div class="user-control">
                      <% if not operator?%>
                          <%= link_to "Register", new_user_path,:class=>"btn btn-default" %><%end%>
                          <%= link_to users_logout_path,:class=>"btn btn-default" do %><i class="fa fa-sign-out fa-2x"></i>
                          <%end%>
                    </div>
                </div>
            </div>
          
        </div>
    </div>
    

<div class="container-fluid">
  <div class="row  wrapper">
      <div class="col-md-2 col-sm-4 col-xs-12 sidebar">
            <div class="panel-collapse  panel-scroll" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><%= image_tag "dash-icon.png",:style=>"margin-top:8%;" %><%= link_to "  Dashboard",users_dashboard_path %></a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
                           
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><%= image_tag "nvetory-icon.png"%> Inventory</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse ">
                        <div class="panel-body">
                          <ul>
                              <li><a href="#"><%= link_to " Order Summary",users_index_orderSummary_path %></a></li>
                                <li><a href="#"><%= link_to " Purchase",users_index_purchase_path %></a></li>
                                <li><a href="#"><%= link_to " Issues",users_index_issues_path %></a></li>
                            <li><a href="#"><%= link_to " Production Report",users_index_productionReport_path %></a></li>
                                <li><a href="#"><%= link_to " Labour",users_index_labour_path %></a></li>
                                <li><a href="#"><%= link_to " Machine Maintenance",users_index_machineMaintenance_path%></a></li>
                                <li><a href="#"><%= link_to " Pending Orders",users_pending_order_path%></a></li>

                                                                
                            </ul>
                           
                        </div>
                    </div>
                </div>
                 <% if not operator?%>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><%= image_tag "report-icon.png"%> Report</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse ">
                        <div class="panel-body">
                          <ul>
                        <li><a href="#"><%= link_to " Order Summary",users_report_order_summary_path%></a></li>
                          <li><a href="#"><%= link_to " Purchase",users_report_purchase_path%></a></li>
                          <li><a href="#"><%= link_to " Issues",users_report_issues_path%></a></li>
                          <li><a href="#"><%= link_to " Production Report",users_report_production_path%></a></li>
                          <li><a href="#"><%= link_to " Qty After Rg Report",users_report_qty_after_rg_path %></a><li>
                          <!--li><a href="#"><!%= link_to " Labour Report",users_lab_report_path%></a></li-->
                          <li><a href="#"><%= link_to " Idle Time Analysis",users_report_idle_time_path %></a></li>
                          <li><a href="#"><%= link_to " Machine Maintenance",users_report_machine_maintenance_path %></a></li>
                          <li><a href="#"><%= link_to " Mould Run History",users_report_mould_history_path %></a></li>
                          <li><a href="#"><%= link_to " Rejection Analysis",users_report_rejection_analysis_path %></a></li>
                          <li><a href="#"><%= link_to " Yield and Cost",users_yield_cost_path%></a></li>
                          <li><a href="#"><%= link_to " OEE Report",users_report_oee_path %></a></li>
                                                                                                
                            </ul>
                           
                        </div>
                    </div>
                </div>
             <%end%>
              <% if factory?%>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><%= image_tag "factory-icon.png"%> Factory</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                       <div class="panel-body">
                          <ul>
                                <li><a href="#"><%= link_to " Colour Issues",users_chemical_new_path%></a></li>
                                <li><a href="#"><%= link_to " Cycle Time",users_machine_time_path%></a></li>
                                <li><a href="#"><%= link_to " Finished Goods Name",users_goods_new_path%></a></li>
                                <li><a href="#"><%= link_to " Insert Material",users_insert_material_new_path%></a></li>
                                <li><a href="#"><%= link_to " Machine Used",users_mach_use_new_path%></a></li>
                                <li><a href="#"><%= link_to " Mould No",users_mould_new_path%></a></li>
                                <li><a href="#"><%= link_to " Nature of Work",users_nature_new_path%></a></li>
                                <li><a href="#"><%= link_to " Party Order", users_party_order_new_path %></a></li>
                                <li><a href="#"><%= link_to " Party Purchase",users_party_purchase_new_path%></a></li>
                                <li><a href="#"><%= link_to " Power of Cost per Unit",users_cost_new_path%></a></li>
                                <li><a href="#"><%= link_to " Raw Material",users_raw_material_new_path%></a></li>
                                <li><a href="#"><%= link_to " Reason For Idle Time",users_reason_for_idle_new_path%></a></li>
                                <li><a href="#"><%= link_to " Reground Issues",users_reground_new_path%></a></li>
                                <li><a href="#"><%= link_to " Rejection Reasons",users_rejection_reason_new_path%></a></li>
                                <li><a href="#"><%= link_to " Supervisor Name",users_supervisor_name_path %></a></li>
                                <li><a href="#"><%= link_to " Type of Coloring Agent",users_chemical_type_new_path%></a></li>
                                <li><a href="#"><%= link_to " Type of Purchase",users_purchase_type_new_path%></a></li>
                                                                
                            </ul>
                           
                        </div>
                    </div>
                </div>
               
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive"><%= image_tag "trash-icon.png"%>
               Trash</a>
                        </h4>
                    </div>
                    <div id="collapseFive" class="panel-collapse collapse">
                       <div class="panel-body">
                          <ul>
                              <li><a href="#"><%= link_to " Order Summary",users_trash_orderSummary_path%></a></li>
                               <li><a href="#"><%= link_to "  Purchase",users_trash_purchase_path%></a></li>
                                <li><a href="#"><%= link_to " Issues",users_trash_issue_path%></a></li>
                                <li><a href="#"><%= link_to " Production Report",users_trash_production_path%></a></li>
                                <li><a href="#"><%= link_to "  Labour",users_trash_labour_path%></a></li>
                                <li><a href="#"><%= link_to "  Machine Maintenance",users_trash_machine_maintenance_path%></a></li>
                                                                
                            </ul>
                           
                        </div>
                    </div>
                </div>
<%end%>
            </div>
     
        </div>
            
            <div class="bod">  
    <div class="clearfix"></div>

    
    
    
<div class="page-footer">
  © 2016 White Plaast 
</div>
    <!--script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/scripts.js"></script-->
  </body>
</html>

<script>
$(".sandwich").click(function(){
    $(".sidebar").toggleClass("show-nav");
  $(".body-wrap").toggleClass("full-width");  
}); 
</script>
<%end%>